#!/usr/bin/env python3
"""Validate App Store / Google Play screenshot assets before upload.

The script is intentionally dependency-light. It reads PNG/JPEG dimensions from
file headers, understands manifest.store.json generated by export_store_screenshots.py,
and reports store-readiness issues as human text or JSON.
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import math
import re
import struct
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

try:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass


ALLOWED_EXTENSIONS = {".png", ".jpg", ".jpeg"}
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
JPEG_SOF_MARKERS = {
    0xC0,
    0xC1,
    0xC2,
    0xC3,
    0xC5,
    0xC6,
    0xC7,
    0xC9,
    0xCA,
    0xCB,
    0xCD,
    0xCE,
    0xCF,
}

RISK_PATTERNS = [
    r"\bbest\b",
    r"#\s*1\b",
    r"\btop\b",
    r"\bnew\b",
    r"\bfree\b",
    r"\bdiscount\b",
    r"\bsale\b",
    r"\bmillion downloads?\b",
    r"\bdownload now\b",
    r"\binstall now\b",
    r"\bplay now\b",
    r"\btry now\b",
]

ALT_TEXT_BAD_PREFIXES = [
    r"^\s*image of\b",
    r"^\s*photo of\b",
    r"^\s*screenshot of\b",
    r"^\s*picture of\b",
]

LISTING_FIELD_MAP = {
    "app-store": {
        "title": "title",
        "subtitle": "subtitle",
        "keywords": "keywords",
        "promotional_text": "promotional-text",
        "full_description": "description",
    },
    "google-play": {
        "title": "title",
        "short_description": "short-description",
        "full_description": "full-description",
    },
}

LISTING_FIELD_LABELS = {
    "title": "title",
    "subtitle": "subtitle",
    "keywords": "keywords",
    "short_description": "short",
    "full_description": "full",
    "promotional_text": "promotional-text",
}

COMMON_COMPETITOR_BRANDS = {
    "app store",
    "apple",
    "apple health",
    "fitbit",
    "garmin",
    "google",
    "google fit",
    "google play",
    "instagram",
    "play store",
    "samsung health",
    "tiktok",
    "youtube",
}


@dataclass
class Finding:
    severity: str
    rule: str
    target: str
    message: str


@dataclass
class ImageInfo:
    path: str
    fmt: str
    width: int
    height: int
    bytes: int
    alpha: bool = False
    png_color_type: int | None = None
    png_bit_depth: int | None = None


@dataclass
class AssetCandidate:
    target: str
    path: Path | None
    caption: str = ""
    alt_text: str = ""
    platform: str | None = None
    preset: str | None = None
    expected_width: int | None = None
    expected_height: int | None = None
    expected_orientation: str | None = None
    source_manifest: str | None = None
    render_status: str | None = None
    metadata: dict[str, Any] | None = None


def default_skill_dir() -> Path:
    return Path(__file__).resolve().parent.parent


def default_data_dir() -> Path:
    return default_skill_dir() / "data"


def read_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON in {path}: {exc}") from exc


def load_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise SystemExit(f"Data file not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def load_listing_limits(data_dir: Path) -> dict[tuple[str, str], int]:
    rows = load_rows(data_dir / "store-listing-limits.csv")
    limits: dict[tuple[str, str], int] = {}
    for row in rows:
        platform = row.get("platform", "").strip().lower()
        field = row.get("field", "").strip().lower()
        max_chars = int_or_none(row.get("max_chars"))
        if platform and field and max_chars:
            limits[(platform, field)] = max_chars
    return limits


def find_preset(data_dir: Path, name: str | None) -> dict[str, str] | None:
    if not name:
        return None
    wanted = name.strip().lower()
    rows = load_rows(data_dir / "store-screenshot-presets.csv")
    for row in rows:
        if row.get("name", "").strip().lower() == wanted:
            return row
    raise SystemExit(f"Preset not found: {name}")


def int_or_none(value: Any) -> int | None:
    if value in (None, ""):
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def has_png_trns_chunk(path: Path) -> bool:
    with path.open("rb") as handle:
        signature = handle.read(8)
        if signature != PNG_SIGNATURE:
            return False
        while True:
            raw_len = handle.read(4)
            if len(raw_len) != 4:
                return False
            length = struct.unpack(">I", raw_len)[0]
            chunk_type = handle.read(4)
            if len(chunk_type) != 4:
                return False
            if chunk_type == b"tRNS":
                return True
            if chunk_type == b"IEND":
                return False
            handle.seek(length + 4, 1)


def read_png_info(path: Path) -> ImageInfo:
    with path.open("rb") as handle:
        header = handle.read(33)
    if len(header) < 33 or not header.startswith(PNG_SIGNATURE):
        raise ValueError("not a valid PNG")
    if header[12:16] != b"IHDR":
        raise ValueError("PNG IHDR chunk not found")
    width, height = struct.unpack(">II", header[16:24])
    bit_depth = header[24]
    color_type = header[25]
    alpha = color_type in {4, 6} or has_png_trns_chunk(path)
    return ImageInfo(
        path=str(path),
        fmt="png",
        width=width,
        height=height,
        bytes=path.stat().st_size,
        alpha=alpha,
        png_color_type=color_type,
        png_bit_depth=bit_depth,
    )


def read_jpeg_info(path: Path) -> ImageInfo:
    with path.open("rb") as handle:
        if handle.read(2) != b"\xff\xd8":
            raise ValueError("not a valid JPEG")
        while True:
            marker_start = handle.read(1)
            if marker_start == b"":
                break
            if marker_start != b"\xff":
                continue
            marker = handle.read(1)
            while marker == b"\xff":
                marker = handle.read(1)
            if marker == b"":
                break
            marker_id = marker[0]
            if marker_id in {0xD8, 0xD9, 0x01} or 0xD0 <= marker_id <= 0xD7:
                continue
            raw_len = handle.read(2)
            if len(raw_len) != 2:
                break
            segment_len = struct.unpack(">H", raw_len)[0]
            if segment_len < 2:
                break
            if marker_id in JPEG_SOF_MARKERS:
                payload = handle.read(5)
                if len(payload) != 5:
                    break
                height, width = struct.unpack(">HH", payload[1:5])
                return ImageInfo(
                    path=str(path),
                    fmt="jpg",
                    width=width,
                    height=height,
                    bytes=path.stat().st_size,
                    alpha=False,
                )
            handle.seek(segment_len - 2, 1)
    raise ValueError("JPEG dimensions not found")


def read_image_info(path: Path) -> ImageInfo:
    suffix = path.suffix.lower()
    if suffix == ".png":
        return read_png_info(path)
    if suffix in {".jpg", ".jpeg"}:
        return read_jpeg_info(path)
    raise ValueError(f"unsupported extension {suffix or '(none)'}")


def resolve_manifest_path(raw: str, manifest_path: Path) -> Path:
    path = Path(raw)
    if path.is_absolute():
        return path
    return (manifest_path.parent / path).resolve()


def candidates_from_manifest(path: Path) -> list[AssetCandidate]:
    payload = read_json(path)
    outputs = payload.get("outputs")
    if not isinstance(outputs, list):
        raise SystemExit(f"{path} must contain an 'outputs' list.")
    target = payload.get("target") if isinstance(payload.get("target"), dict) else {}
    candidates: list[AssetCandidate] = []
    for index, output in enumerate(outputs, start=1):
        if not isinstance(output, dict):
            continue
        output_id = str(output.get("id") or output.get("screen_name") or f"asset-{index:02d}")
        raw_path = output.get("png_path") or output.get("image_path") or output.get("file")
        image_path = resolve_manifest_path(str(raw_path), path) if raw_path else None
        candidates.append(
            AssetCandidate(
                target=output_id,
                path=image_path,
                caption=str(output.get("caption") or ""),
                alt_text=str(output.get("alt_text") or output.get("alt") or output.get("accessibility_label") or ""),
                platform=str(output.get("platform") or target.get("platform") or "") or None,
                preset=str(output.get("preset") or target.get("preset") or "") or None,
                expected_width=int_or_none(output.get("width") or target.get("width")),
                expected_height=int_or_none(output.get("height") or target.get("height")),
                expected_orientation=str(target.get("orientation") or "") or None,
                source_manifest=str(path),
                render_status=str(output.get("render_status") or output.get("status") or "") or None,
                metadata=output,
            )
        )
    return candidates


def expand_target(raw: str, cwd: Path) -> list[Path]:
    if any(ch in raw for ch in "*?[]"):
        matches = [Path(p).resolve() for p in glob.glob(str(cwd / raw), recursive=True)]
        return matches
    path = Path(raw)
    if not path.is_absolute():
        path = cwd / path
    return [path.resolve()]


def collect_image_files(directory: Path) -> list[Path]:
    files: list[Path] = []
    for path in directory.rglob("*"):
        if path.is_file() and path.suffix.lower() in ALLOWED_EXTENSIONS:
            files.append(path.resolve())
    return sorted(files)


def captions_from_args(args: argparse.Namespace) -> list[str]:
    captions: list[str] = []
    if args.captions:
        separator = "||" if "||" in args.captions else "|"
        captions.extend(part.strip() for part in args.captions.split(separator))
    captions.extend(args.caption or [])
    return [caption for caption in captions if caption]


def alt_texts_from_args(args: argparse.Namespace) -> list[str]:
    alt_texts: list[str] = []
    if args.alt_texts:
        separator = "||" if "||" in args.alt_texts else "|"
        alt_texts.extend(part.strip() for part in args.alt_texts.split(separator))
    alt_texts.extend(args.alt_text or [])
    return [alt_text for alt_text in alt_texts if alt_text]


def candidates_from_targets(args: argparse.Namespace) -> list[AssetCandidate]:
    cwd = Path.cwd()
    candidates: list[AssetCandidate] = []
    captions = captions_from_args(args)
    alt_texts = alt_texts_from_args(args)

    explicit_manifests: list[Path] = []
    if args.manifest:
        explicit_manifests.extend(path.resolve() for path in args.manifest)

    paths: list[Path] = []
    for raw in args.targets or []:
        paths.extend(expand_target(raw, cwd))

    for path in explicit_manifests:
        candidates.extend(candidates_from_manifest(path))

    for path in paths:
        if path.is_dir():
            manifest = path / "manifest.store.json"
            if manifest.exists():
                candidates.extend(candidates_from_manifest(manifest.resolve()))
            else:
                for image in collect_image_files(path):
                    candidates.append(AssetCandidate(target=image.name, path=image))
            continue
        if path.name == "manifest.store.json" or path.suffix.lower() == ".json":
            candidates.extend(candidates_from_manifest(path))
            continue
        candidates.append(AssetCandidate(target=path.name, path=path))

    for index, candidate in enumerate(candidates):
        if not candidate.caption and index < len(captions):
            candidate.caption = captions[index]
        if not candidate.alt_text and index < len(alt_texts):
            candidate.alt_text = alt_texts[index]
    return candidates


def apply_cli_expectations(
    candidates: list[AssetCandidate],
    preset: dict[str, str] | None,
    args: argparse.Namespace,
) -> None:
    width = args.width or int_or_none(preset.get("width") if preset else None)
    height = args.height or int_or_none(preset.get("height") if preset else None)
    platform = args.platform or (preset.get("platform") if preset else None)
    preset_name = args.preset or (preset.get("name") if preset else None)
    orientation = args.orientation or (preset.get("orientation") if preset else None)

    for candidate in candidates:
        if width and height:
            candidate.expected_width = width
            candidate.expected_height = height
        if platform:
            candidate.platform = platform
        if preset_name:
            candidate.preset = preset_name
        if orientation:
            candidate.expected_orientation = orientation


def add(finding_list: list[Finding], severity: str, rule: str, target: str, message: str) -> None:
    finding_list.append(Finding(severity=severity, rule=rule, target=target, message=message))


def ratio_close(actual_w: int, actual_h: int, expected_w: int, expected_h: int, tolerance: float) -> bool:
    if actual_h == 0 or expected_h == 0:
        return False
    actual = actual_w / actual_h
    expected = expected_w / expected_h
    return abs(actual - expected) <= tolerance


def orientation_of(width: int, height: int) -> str:
    if width == height:
        return "square"
    return "portrait" if height > width else "landscape"


def risk_terms(caption: str) -> list[str]:
    hits: list[str] = []
    for pattern in RISK_PATTERNS:
        match = re.search(pattern, caption, flags=re.IGNORECASE)
        if match:
            hits.append(match.group(0))
    return hits


def caption_words(caption: str) -> list[str]:
    return re.findall(r"[\w#]+(?:[-'][\w#]+)?", caption, flags=re.UNICODE)


def collapse_text(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()


def listing_tokens(value: str) -> list[str]:
    return [token.casefold() for token in re.findall(r"[\w]+(?:[-'][\w]+)?", value or "", flags=re.UNICODE)]


def listing_values_from_args(args: argparse.Namespace) -> dict[str, str]:
    values = {
        "title": args.title,
        "subtitle": args.subtitle,
        "keywords": args.keywords,
        "short_description": args.short_description,
        "full_description": args.full_description,
        "promotional_text": args.promotional_text,
    }
    return {key: collapse_text(value) for key, value in values.items() if collapse_text(value)}


def has_listing_text(args: argparse.Namespace) -> bool:
    return bool(listing_values_from_args(args))


def infer_listing_platform(args: argparse.Namespace, candidates: list[AssetCandidate]) -> str | None:
    if args.platform:
        return args.platform
    platforms = sorted(set((candidate.platform or "").lower() for candidate in candidates if candidate.platform))
    if len(platforms) == 1:
        return platforms[0]
    return None


def split_keywords(value: str) -> list[str]:
    return [collapse_text(part).casefold() for part in value.split(",") if collapse_text(part)]


def listing_report(args: argparse.Namespace, candidates: list[AssetCandidate]) -> dict[str, Any] | None:
    values = listing_values_from_args(args)
    if not values:
        return None
    return {
        "platform": infer_listing_platform(args, candidates),
        "locale": args.locale,
        "fields": {LISTING_FIELD_LABELS.get(key, key): value for key, value in values.items()},
    }


def check_listing_text(args: argparse.Namespace, candidates: list[AssetCandidate]) -> list[Finding]:
    findings: list[Finding] = []
    values = listing_values_from_args(args)
    if not values:
        return findings

    platform = infer_listing_platform(args, candidates)
    if not platform:
        add(
            findings,
            "fail",
            "listing_platform_missing",
            "listing",
            "Listing text checks need --platform app-store or --platform google-play, or a manifest with one clear platform.",
        )
        return findings

    field_map = LISTING_FIELD_MAP.get(platform, {})
    limits = load_listing_limits(args.data)
    normalized: dict[str, str] = {}
    for cli_field, value in values.items():
        platform_field = field_map.get(cli_field)
        label = LISTING_FIELD_LABELS.get(cli_field, cli_field)
        if not platform_field:
            add(
                findings,
                "fail",
                "unsupported_listing_field",
                "listing",
                f"--{label} is not a {platform} listing field. Use the platform's native metadata fields only.",
            )
            continue
        normalized[platform_field] = value
        limit = limits.get((platform, platform_field))
        if limit and len(value) > limit:
            add(
                findings,
                "fail",
                "listing_char_limit",
                "listing",
                f"{platform} {platform_field} has {len(value)} characters; limit is {limit}.",
            )
        risky = risk_terms(value)
        if risky:
            add(
                findings,
                "warn",
                "listing_risky_claim",
                "listing",
                f"{platform} {platform_field} contains store-risk wording: {', '.join(sorted(set(risky)))}.",
            )

    if not args.locale:
        add(
            findings,
            "info",
            "listing_locale_missing",
            "listing",
            "No --locale supplied. Validate localized title, subtitle, keyword, short, and full-description variants separately.",
        )

    store_or_third_party_terms = {brand.casefold() for brand in COMMON_COMPETITOR_BRANDS}
    competitor_brands = {brand.casefold() for brand in (args.competitor_brand or []) if brand.strip()}
    for field, value in normalized.items():
        haystack = value.casefold()
        store_hits = sorted(brand for brand in store_or_third_party_terms if brand and brand in haystack)
        if store_hits:
            add(
                findings,
                "warn",
                "third_party_brand_in_listing",
                "listing",
                f"{platform} {field} contains store/third-party brand wording: {', '.join(store_hits)}. Keep only if it is a verified integration, compatibility claim, or legal use.",
            )
        competitor_hits = sorted(brand for brand in competitor_brands if brand and brand in haystack)
        if competitor_hits:
            add(
                findings,
                "fail",
                "competitor_brand_in_listing",
                "listing",
                f"{platform} {field} contains blocked competitor brand wording: {', '.join(competitor_hits)}.",
            )

    if platform == "app-store" and "keywords" in normalized:
        keywords = split_keywords(normalized["keywords"])
        duplicate_keywords = sorted({keyword for keyword in keywords if keywords.count(keyword) > 1})
        if duplicate_keywords:
            add(
                findings,
                "fail",
                "duplicate_keywords",
                "listing",
                f"App Store keywords repeat: {', '.join(duplicate_keywords)}.",
            )

        visible_text = " ".join(normalized.get(field, "") for field in ["title", "subtitle"])
        visible_tokens = {token for token in listing_tokens(visible_text) if len(token) > 2}
        keyword_tokens = {token for keyword in keywords for token in listing_tokens(keyword) if len(token) > 2}
        overlaps = sorted(visible_tokens & keyword_tokens)
        if overlaps:
            add(
                findings,
                "fail",
                "keyword_repeats_visible_metadata",
                "listing",
                f"App Store keywords repeat title/subtitle terms: {', '.join(overlaps)}.",
            )

    return findings


def estimate_caption_area_percent(caption: str, width: int | None, height: int | None) -> float:
    if not caption.strip():
        return 0.0
    safe_width = width or 1080
    safe_height = height or 1920
    chars_per_line = max(14, int(safe_width / 54))
    lines = max(1, math.ceil(len(caption) / chars_per_line))
    line_height = max(52, safe_height * 0.038)
    padding = safe_height * 0.045
    return ((lines * line_height + padding) / safe_height) * 100


def check_caption(candidate: AssetCandidate, args: argparse.Namespace, findings: list[Finding]) -> None:
    caption = (candidate.caption or "").strip()
    target = candidate.target
    if not caption:
        return

    risks = risk_terms(caption)
    if risks:
        add(
            findings,
            "fail",
            "risky_aso_claim",
            target,
            f"Caption contains store-risk wording: {', '.join(sorted(set(risks)))}.",
        )

    words = caption_words(caption)
    if len(words) > args.max_caption_words_hard:
        add(findings, "fail", "caption_too_long", target, f"Caption has {len(words)} words; hard limit is {args.max_caption_words_hard}.")
    elif len(words) > args.max_caption_words:
        add(findings, "warn", "caption_word_count", target, f"Caption has {len(words)} words; target is {args.max_caption_words} or fewer.")

    if len(caption) > args.max_caption_chars_hard:
        add(findings, "fail", "caption_char_count", target, f"Caption has {len(caption)} characters; hard limit is {args.max_caption_chars_hard}.")
    elif len(caption) > args.max_caption_chars:
        add(findings, "warn", "caption_char_count", target, f"Caption has {len(caption)} characters; target is {args.max_caption_chars} or fewer.")

    measured_area = None
    if candidate.metadata:
        measured_area = candidate.metadata.get("caption_area_percent") or candidate.metadata.get("text_area_percent")
    area = float(measured_area) if measured_area is not None else estimate_caption_area_percent(
        caption,
        candidate.expected_width,
        candidate.expected_height,
    )
    if area > args.max_caption_area_percent * 1.5:
        add(findings, "fail", "caption_area", target, f"Caption is estimated at {area:.1f}% of the image; limit is {args.max_caption_area_percent:.1f}%.")
    elif area > args.max_caption_area_percent:
        add(findings, "warn", "caption_area", target, f"Caption is estimated at {area:.1f}% of the image; target is {args.max_caption_area_percent:.1f}% or less.")

    expanded = len(caption) * args.locale_expansion
    if expanded > args.max_caption_chars_hard:
        add(
            findings,
            "warn",
            "localization_expansion",
            target,
            f"Localized text could expand to about {expanded:.0f} characters; rewrite shorter or plan multi-line layout.",
        )


def check_alt_text(candidate: AssetCandidate, args: argparse.Namespace, findings: list[Finding]) -> None:
    platform = (candidate.platform or "").lower()
    target = candidate.target
    alt_text = (candidate.alt_text or "").strip()
    if platform != "google-play" and not alt_text:
        return
    if not alt_text:
        severity = "fail" if args.require_alt_text else "warn"
        add(
            findings,
            severity,
            "missing_alt_text",
            target,
            "Google Play assets should include concise alt text for screenshots and graphics.",
        )
        return
    if len(alt_text) > args.max_alt_text_chars:
        add(findings, "fail", "alt_text_length", target, f"Alt text has {len(alt_text)} characters; limit is {args.max_alt_text_chars}.")
    for pattern in ALT_TEXT_BAD_PREFIXES:
        if re.search(pattern, alt_text, flags=re.IGNORECASE):
            add(findings, "warn", "alt_text_generic_prefix", target, "Alt text should not start with generic phrases like 'image of' or 'photo of'.")
            break
    risks = risk_terms(alt_text)
    if risks:
        add(
            findings,
            "warn",
            "alt_text_risky_claim",
            target,
            f"Alt text contains store-risk wording: {', '.join(sorted(set(risks)))}.",
        )


def check_google_play_rules(candidate: AssetCandidate, info: ImageInfo, findings: list[Finding]) -> None:
    target = candidate.target
    preset = (candidate.preset or "").lower()
    feature_graphic = "feature-graphic" in preset or "feature graphic" in preset

    if info.fmt == "png":
        if info.alpha:
            add(findings, "fail", "png_alpha", target, "Google Play requires JPEG or 24-bit PNG with no alpha/transparency.")
        if info.png_color_type not in {2, None}:
            add(findings, "warn", "png_color_type", target, f"PNG color type {info.png_color_type} may not be 24-bit truecolor; Google Play prefers 24-bit PNG.")

    if feature_graphic:
        if (info.width, info.height) != (1024, 500):
            add(findings, "fail", "feature_graphic_size", target, f"Google Play feature graphic must be 1024x500, got {info.width}x{info.height}.")
        return

    min_dim = min(info.width, info.height)
    max_dim = max(info.width, info.height)
    if min_dim < 320:
        add(findings, "fail", "google_min_dimension", target, f"Minimum dimension is {min_dim}px; Google Play screenshots need at least 320px.")
    if max_dim > 3840:
        add(findings, "fail", "google_max_dimension", target, f"Maximum dimension is {max_dim}px; Google Play screenshots allow up to 3840px.")
    if max_dim > min_dim * 2:
        add(findings, "fail", "google_aspect_limit", target, f"Aspect ratio {max_dim}:{min_dim} exceeds Google Play's 2:1 screenshot limit.")


def check_asset(candidate: AssetCandidate, args: argparse.Namespace) -> tuple[ImageInfo | None, list[Finding]]:
    findings: list[Finding] = []
    target = candidate.target

    if candidate.path is None:
        add(
            findings,
            "fail",
            "missing_image",
            target,
            "Manifest output has no PNG/JPG path. Render with export_store_screenshots.py --render playwright before final QA.",
        )
        check_caption(candidate, args, findings)
        check_alt_text(candidate, args, findings)
        return None, findings

    if not candidate.path.exists():
        add(findings, "fail", "missing_image_file", target, f"Image file not found: {candidate.path}.")
        check_caption(candidate, args, findings)
        check_alt_text(candidate, args, findings)
        return None, findings

    suffix = candidate.path.suffix.lower()
    if suffix not in ALLOWED_EXTENSIONS:
        add(findings, "fail", "image_format", target, f"Only PNG/JPG/JPEG are store-safe here; got {suffix or '(none)'}.")
        check_caption(candidate, args, findings)
        check_alt_text(candidate, args, findings)
        return None, findings

    try:
        info = read_image_info(candidate.path)
    except ValueError as exc:
        add(findings, "fail", "image_parse", target, f"Could not read image header: {exc}.")
        check_caption(candidate, args, findings)
        check_alt_text(candidate, args, findings)
        return None, findings

    max_bytes = args.max_file_mb * 1024 * 1024
    if info.bytes > max_bytes:
        add(findings, "warn", "file_size", target, f"File is {info.bytes / (1024 * 1024):.2f} MB; target maximum is {args.max_file_mb:.1f} MB.")

    if candidate.expected_width and candidate.expected_height:
        if (info.width, info.height) != (candidate.expected_width, candidate.expected_height):
            add(
                findings,
                "fail",
                "dimension_mismatch",
                target,
                f"Expected {candidate.expected_width}x{candidate.expected_height}, got {info.width}x{info.height}.",
            )
        elif not ratio_close(info.width, info.height, candidate.expected_width, candidate.expected_height, args.ratio_tolerance):
            add(
                findings,
                "fail",
                "aspect_ratio",
                target,
                f"Expected aspect ratio {candidate.expected_width}:{candidate.expected_height}, got {info.width}:{info.height}.",
            )

    expected_orientation = (candidate.expected_orientation or "").lower()
    if expected_orientation and expected_orientation != "any":
        actual_orientation = orientation_of(info.width, info.height)
        if expected_orientation != actual_orientation:
            add(findings, "fail", "orientation_mismatch", target, f"Expected {expected_orientation}, got {actual_orientation}.")

    platform = (candidate.platform or "").lower()
    if platform == "app-store" and not (candidate.expected_width and candidate.expected_height):
        add(
            findings,
            "fail",
            "app_store_exact_size_unknown",
            target,
            "App Store screenshots must match exact accepted dimensions. Provide --preset or --width/--height; presetless App Store checks cannot confirm upload-valid size.",
        )
    if platform == "google-play":
        check_google_play_rules(candidate, info, findings)

    check_caption(candidate, args, findings)
    check_alt_text(candidate, args, findings)
    return info, findings


def check_set(candidates: list[AssetCandidate], infos: list[ImageInfo], args: argparse.Namespace) -> list[Finding]:
    findings: list[Finding] = []
    if not candidates:
        add(findings, "fail", "no_assets", "set", "No assets found. Pass image files, a directory, or manifest.store.json.")
        return findings

    min_count = args.min_count if args.min_count is not None else 1
    if len(candidates) < min_count:
        add(findings, "fail", "missing_screenshot_count", "set", f"Found {len(candidates)} asset(s); expected at least {min_count}.")

    platforms = sorted(set((candidate.platform or "").lower() for candidate in candidates if candidate.platform))
    if "app-store" in platforms and len(candidates) > 10:
        add(findings, "fail", "app_store_count", "set", f"App Store accepts up to 10 screenshots; found {len(candidates)}.")
    if "google-play" in platforms and len(candidates) < 2:
        add(findings, "warn", "google_play_minimum_count", "set", "Google Play requires at least 2 screenshots across supported device types.")

    orientations = sorted(set(orientation_of(info.width, info.height) for info in infos))
    expected = sorted(set((candidate.expected_orientation or "").lower() for candidate in candidates if candidate.expected_orientation and candidate.expected_orientation != "any"))
    if not expected and len(orientations) > 1:
        add(findings, "warn", "mixed_orientation", "set", f"Assets mix orientations: {', '.join(orientations)}. Keep a store set deliberately portrait or landscape unless platform-specific.")
    return findings


def make_report(
    candidates: list[AssetCandidate],
    infos: list[ImageInfo],
    findings: list[Finding],
    strict: bool,
    listing: dict[str, Any] | None = None,
) -> dict[str, Any]:
    fail_count = sum(1 for finding in findings if finding.severity == "fail")
    warn_count = sum(1 for finding in findings if finding.severity == "warn")
    info_count = sum(1 for finding in findings if finding.severity == "info")
    return {
        "ok": fail_count == 0 and (warn_count == 0 or not strict),
        "strict": strict,
        "summary": {
            "assets": len(candidates),
            "readable_images": len(infos),
            "fail": fail_count,
            "warn": warn_count,
            "info": info_count,
        },
        "assets": [
            {
                "target": candidate.target,
                "path": str(candidate.path) if candidate.path else None,
                "caption": candidate.caption,
                "alt_text": candidate.alt_text,
                "platform": candidate.platform,
                "preset": candidate.preset,
                "expected_width": candidate.expected_width,
                "expected_height": candidate.expected_height,
                "expected_orientation": candidate.expected_orientation,
                "source_manifest": candidate.source_manifest,
                "render_status": candidate.render_status,
            }
            for candidate in candidates
        ],
        "images": [asdict(info) for info in infos],
        "listing_text": listing,
        "findings": [asdict(finding) for finding in findings],
    }


def print_human_report(report: dict[str, Any]) -> None:
    summary = report["summary"]
    print("Store Asset QA")
    print(f"Assets: {summary['assets']}  Readable images: {summary['readable_images']}")
    print(f"Fails: {summary['fail']}  Warnings: {summary['warn']}  Info: {summary['info']}")
    if report.get("listing_text"):
        listing = report["listing_text"]
        fields = ", ".join(sorted((listing.get("fields") or {}).keys()))
        print(f"Listing: {listing.get('platform') or 'unknown'} {listing.get('locale') or ''} ({fields})")
    if not report["findings"]:
        print("Result: PASS")
        return
    print("")
    for finding in report["findings"]:
        severity = finding["severity"].upper()
        print(f"[{severity}] {finding['rule']} :: {finding['target']}")
        print(f"  {finding['message']}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate store screenshot assets and manifest.store.json outputs.")
    parser.add_argument("targets", nargs="*", help="Image files, directories, globs, or manifest.store.json files.")
    parser.add_argument("--manifest", type=Path, action="append", help="manifest.store.json generated by export_store_screenshots.py. Repeatable.")
    parser.add_argument("--data", type=Path, default=default_data_dir(), help="Directory containing store-screenshot-presets.csv.")
    parser.add_argument("--preset", help="Store preset name from data/store-screenshot-presets.csv.")
    parser.add_argument("--platform", choices=["app-store", "google-play"], help="Override platform for direct image checks.")
    parser.add_argument("--orientation", choices=["portrait", "landscape", "square", "any"], help="Expected orientation for direct image checks.")
    parser.add_argument("--width", type=int, help="Expected exact image width.")
    parser.add_argument("--height", type=int, help="Expected exact image height.")
    parser.add_argument("--caption", action="append", default=[], help="Caption for direct image checks. Repeat for multiple images.")
    parser.add_argument("--captions", help="Pipe-separated captions, e.g. 'Plan your week|Review every task'.")
    parser.add_argument("--alt-text", action="append", default=[], help="Google Play alt text for direct image checks. Repeat for multiple images.")
    parser.add_argument("--alt-texts", help="Pipe-separated Google Play alt text values.")
    parser.add_argument("--require-alt-text", action="store_true", help="Fail Google Play assets that have no alt text instead of warning.")
    parser.add_argument("--title", help="Store listing title/app name text to validate.")
    parser.add_argument("--subtitle", help="App Store subtitle text to validate.")
    parser.add_argument("--keywords", help="App Store comma-separated keyword field to validate.")
    parser.add_argument("--short", dest="short_description", help="Google Play short description text to validate.")
    parser.add_argument("--full", dest="full_description", help="Full store description text to validate.")
    parser.add_argument("--promotional-text", help="App Store promotional text to validate.")
    parser.add_argument("--competitor-brand", action="append", default=[], help="Competitor/third-party brand term that must not appear in listing text. Repeatable.")
    parser.add_argument("--locale", help="Listing locale/language code, e.g. en-US or tr-TR.")
    parser.add_argument("--min-count", type=int, help="Required minimum number of assets in the set.")
    parser.add_argument("--max-file-mb", type=float, default=8.0, help="Warn when a file exceeds this size. Default: 8 MB.")
    parser.add_argument("--ratio-tolerance", type=float, default=0.01, help="Allowed aspect-ratio drift when exact dimensions are not enough.")
    parser.add_argument("--max-caption-words", type=int, default=6, help="Recommended caption word limit. Default: 6.")
    parser.add_argument("--max-caption-words-hard", type=int, default=12, help="Fail caption word limit. Default: 12.")
    parser.add_argument("--max-caption-chars", type=int, default=64, help="Recommended caption character limit. Default: 64.")
    parser.add_argument("--max-caption-chars-hard", type=int, default=110, help="Fail caption character limit. Default: 110.")
    parser.add_argument("--max-caption-area-percent", type=float, default=20.0, help="Warn/fail when captions dominate too much of the asset.")
    parser.add_argument("--locale-expansion", type=float, default=1.5, help="Estimated localized text expansion multiplier. Default: 1.5.")
    parser.add_argument("--max-alt-text-chars", type=int, default=140, help="Google Play alt text character limit. Default: 140.")
    parser.add_argument("--strict", action="store_true", help="Return non-zero for warnings as well as failures.")
    parser.add_argument("--json", action="store_true", help="Print JSON report instead of human text.")
    parser.add_argument("--out", type=Path, help="Optional path to write the JSON report.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    listing_requested = has_listing_text(args)
    if not args.targets and not args.manifest and not listing_requested:
        parser.error("Pass at least one target image/directory/manifest, --manifest, or listing text fields such as --title/--short.")

    preset = find_preset(args.data, args.preset)
    candidates = candidates_from_targets(args)
    apply_cli_expectations(candidates, preset, args)

    all_findings: list[Finding] = []
    infos: list[ImageInfo] = []
    for candidate in candidates:
        info, findings = check_asset(candidate, args)
        all_findings.extend(findings)
        if info:
            infos.append(info)
    if candidates:
        all_findings.extend(check_set(candidates, infos, args))
    all_findings.extend(check_listing_text(args, candidates))

    report = make_report(candidates, infos, all_findings, args.strict, listing_report(args, candidates))
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    if args.json:
        print(json.dumps(report, indent=2, ensure_ascii=False))
    else:
        print_human_report(report)

    summary = report["summary"]
    if summary["fail"] > 0 or (args.strict and summary["warn"] > 0):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
